package.path=package.path..";./?.lua;./engine/?.lua"
local loader=require("engine.data.loader");local S=require("engine.session");local I=require("engine.interpreter");local E=require("engine.exploration");local director=require("engine.director");local p,f=0,0;local function check(v,m)if v then p=p+1;print("  [PASS] "..m)else f=f+1;print("  [FAIL] "..m)end end;loader.init()
local function load(s,id)E.loadMap(s,assert(loader.getMapIndex(id)))end;local function find(id,name,s)local map=s and s.currentMapData and s.currentMapData.id==id and s.currentMapData or loader.maps[loader.getMapIndex(id)];for _,v in ipairs(map.events or{})do if v.name==name then return v end end end
local function run(s,v)
 local resolved=E.resolvePage(v,s);local ctx={session=s,loader=loader,events={},party=s.party or{},event=resolved};local graph=I.runInteractive(resolved.commands or{},ctx);local walker=director.GraphWalker.new(s,graph);local guard=0
 while walker:getCurrentNode() do
  guard=guard+1;if guard>100 then error("metro Event graph did not terminate") end
  local node=walker:getCurrentNode()
  if node.type=="ACTION" and node.action=="RUN_IMMEDIATE" then I.runImmediate(node.commands or{},ctx);walker:advance()
  elseif node.type=="TEXT" then walker:advance()
  elseif node.type=="CHOICE" then walker:selectChoice(1)
  elseif node.type=="ACTION" and node.action=="START_BATTLE" then return node,resolved
  else walker:advance() end
 end
 return nil,resolved
end
for id=32,36 do local map=loader.maps[loader.getMapIndex(id)];check(map and map.id==id,"metro map "..id.." registered");local t;for _,v in ipairs(map.events or{})do if v.mover then t=v break end end;check(t and t.mover.type=="path","map "..id.." authors path mover");check(t and #t.mover.footprint==9 and #t.mover.ports==3,"map "..id.." authors footprint and ports");check(t and t.mover.visual.models.open and t.mover.visual.models.closed,"map "..id.." authors visual states")end
local s=S.GameSession.new(loader);s:initializeStartingParty();load(s,33);local gate=find(33,"Klabin Service Gate",s);run(s,gate);check(s.flags.metro_klabin_unlocked~=true,"Klabin locked before key");load(s,34);local locker=find(34,"Bras Track Locker",s);run(s,locker);check(s.flags.metro_track_key~=true,"locker refuses key before power");run(s,find(34,"Bras Auxiliary Breaker",s));check(s.flags.metro_aux_power==true,"breaker Event restores power");run(s,locker);check(s.flags.metro_track_key==true,"locker Event grants key");load(s,33);gate=find(33,"Klabin Service Gate",s);run(s,gate);check(s.flags.metro_klabin_unlocked==true,"Klabin Event opens after key")
local neg=S.GameSession.new(loader);neg:initializeStartingParty();load(neg,35);local vault=find(35,"Faria Lima Vault",neg);local ng=neg.gold;run(neg,vault);check(neg.flags.metro_master_pass~=true and neg.gold==ng,"vault refuses reward without power");load(s,35);vault=find(35,"Faria Lima Vault",s);local bg=s.gold;run(s,vault);check(s.flags.metro_master_pass==true and s.gold==bg+10000,"vault Event grants pass and gold");run(s,vault);check(s.gold==bg+10000,"vault cleared branch prevents duplicate reward");load(s,36);run(s,find(36,"Terminal Access",s));check(s.flags.metro_boss_access==true,"terminal opens after both prerequisites");local boss=find(36,"O Tatuzao",s);local resolved=E.resolvePage(boss,s);check(resolved.commands[1]and resolved.commands[1].cmd=="BATTLE","boss resolves to battle page");local graph=I.runInteractive(resolved.commands,{session=s,loader=loader,events={},party=s.party});local bn;for _,n in pairs(graph.nodes or{})do if n.action=="START_BATTLE"then bn=n break end end;check(bn and bn.troop=="boss_red_dragon","interpreter compiles real boss battle");local bc=resolved.commands[1];check(bc.onVictory and bc.onVictory[1]and bc.onVictory[1].flag=="metro_stratum_solved","boss victory branch wired to completion");I.runImmediate(bc.onVictory,{session=s,loader=loader,events={},party=s.party});check(s.flags.metro_stratum_solved==true,"authored boss victory branch sets completion");run(s,find(36,"Santa Cruz Emergency Corridor",s));check(s.flags.metro_shortcut_unlocked==true and s.currentMapData.id==32,"shortcut Event unlocks and returns to Blue")
print(string.format("=== Metro Stratum Tests: %d passed, %d failed ===",p,f));if f>0 then require("tests.fail_fast")("test_metro_stratum",f,p)end
