"""Generate the PE Day 1 rough chapter (#1427) from rooms.json.

    python projects/pe-day1/tools/chapter/build_chapter.py

rooms.json is the single authority. This writes, deterministically:
  data/scenes/day1_<room>.json      one zero-SCRIPT Scene per room
  data/scenes/index.json            registers them (other entries kept)
  assets/models/blockout/*.obj|mtl  coloured blockout rooms and enemies

Exploration owns only where Aya walks (sceneState.walkX/walkY). While a fight
runs, every domain fact is read from rt.* exactly as basement_rat does; the
walk position is copied back from rt only when the fight ends.
"""
import json
import re
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.normpath(os.path.join(HERE, "..", ".."))
SCENES = os.path.join(PROJECT, "data", "scenes")
BLOCKOUT = os.path.join(PROJECT, "assets", "models", "blockout")
BACKSTAGE = "assets/models/backstage/"
AYA = "assets/models/aya/"
BOSSES = "assets/models/bosses/"

WALK_SPEED = 0.05          # world units per fixed tick while exploring
NEAR = 0.9                 # interaction radius for doors and pickups
CORRIDOR_BOUNDS = {"minX": -2.2, "maxX": 2.2, "minY": 0.3, "maxY": 4.4}
CORRIDOR_CAMERA = {"position": [2, -7.2, 5.4], "target": [0, 2.6, 0.35], "fov": 40}

PALETTES = {  # floor, wall, trim (blockout colours, not art)
    "lobby":     ([0.42, 0.10, 0.10], [0.62, 0.52, 0.38], [0.80, 0.66, 0.30]),
    "hall":      ([0.36, 0.08, 0.09], [0.55, 0.42, 0.30], [0.78, 0.62, 0.28]),
    "stage":     ([0.40, 0.28, 0.16], [0.18, 0.06, 0.08], [0.70, 0.55, 0.25]),
    "backstage": ([0.30, 0.30, 0.28], [0.52, 0.47, 0.40], [0.80, 0.74, 0.60]),
    "dressing":  ([0.34, 0.26, 0.20], [0.60, 0.55, 0.48], [0.82, 0.76, 0.62]),
    "rehearsal": ([0.38, 0.27, 0.17], [0.50, 0.46, 0.40], [0.75, 0.70, 0.58]),
    "sewer":     ([0.16, 0.20, 0.16], [0.30, 0.31, 0.27], [0.22, 0.26, 0.22]),
    "street":    ([0.30, 0.30, 0.32], [0.20, 0.22, 0.30], [0.85, 0.85, 0.90]),
}


def q(text):
    """A Formula string literal."""
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def setv(**kv):
    return {"cmd": "SET_SCENE_STATE", "assignments": [{"name": k, "value": v} for k, v in kv.items()]}


def iff(cond, then, other=None):
    out = {"cmd": "IF", "condition": cond, "then": then}
    if other:
        out["else"] = other
    return out


# --- geometry -----------------------------------------------------------------

class Obj:
    def __init__(self, mtllib):
        self.lines = ["# generated by build_chapter.py from rooms.json", "mtllib " + mtllib]
        self.n = 0

    def box(self, mat, cx, cy, cz, sx, sy, sz):
        """World box (x right, y depth, z up), written OBJ Y-up like Blender."""
        self.lines.append("usemtl " + mat)
        hx, hy, hz = sx / 2, sy / 2, sz / 2
        for dx in (-hx, hx):
            for dy in (-hy, hy):
                for dz in (-hz, hz):
                    x, y, z = cx + dx, cy + dy, cz + dz
                    self.lines.append("v %.4f %.4f %.4f" % (x, z, -y))
        b = self.n
        # corner index = 1 + 4*ix + 2*iy + iz
        for f in ((0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)):
            self.lines.append("f " + " ".join(str(b + i + 1) for i in f))
        self.n += 8

    def write(self, path):
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(self.lines) + "\n")


def write_mtl(path, mats):
    out = ["# generated by build_chapter.py"]
    for name, kd in sorted(mats.items()):
        out += ["newmtl " + name, "Ka 1 1 1", "Kd %.3f %.3f %.3f" % tuple(kd), "Ks 0.1 0.1 0.1", "d 1", "illum 2", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))


def room_dims(room):
    w, d = room["size"]
    return w, d


def bounds_of(room):
    if room.get("corridor"):
        return dict(CORRIDOR_BOUNDS)
    w, d = room_dims(room)
    return {"minX": -w / 2 + 0.4, "maxX": w / 2 - 0.4, "minY": 0.3, "maxY": d - 0.4}


def door_point(room, door):
    b = bounds_of(room)
    wall, at = door["wall"], door["at"]
    return {"back": (at, b["maxY"]), "front": (at, b["minY"]),
            "left": (b["minX"], at), "right": (b["maxX"], at)}[wall]


def build_room_obj(room, mats):
    w, d = room_dims(room)
    pal = room["palette"]
    floor, wall, trim = PALETTES[pal]
    mats[pal + "_floor"], mats[pal + "_wall"], mats[pal + "_trim"] = floor, wall, trim
    mats["door_red"], mats["door_locked"] = [0.70, 0.08, 0.06], [0.25, 0.25, 0.28]
    o = Obj("blockout.mtl")
    o.box(pal + "_floor", 0, d / 2, -0.05, w, d, 0.1)
    o.box(pal + "_wall", 0, d + 0.1, 1.5, w + 0.4, 0.2, 3.0)            # back
    o.box(pal + "_wall", -w / 2 - 0.1, d / 2, 1.5, 0.2, d, 3.0)         # left
    o.box(pal + "_wall", w / 2 + 0.1, d / 2, 1.5, 0.2, d, 3.0)          # right
    o.box(pal + "_trim", 0, -0.05, 0.1, w + 0.4, 0.1, 0.2)              # front curb only
    for door in room["doors"]:
        x, y = door_point(room, door)
        mat = "door_locked" if door.get("needs") else "door_red"
        if door["wall"] == "back":
            o.box(mat, x, d, 1.1, 1.2, 0.1, 2.2)
        elif door["wall"] == "front":
            o.box(mat, x, 0.0, 0.03, 1.2, 0.6, 0.06)                     # threshold mat
        else:
            sx = -w / 2 if door["wall"] == "left" else w / 2
            o.box(mat, sx, y, 1.1, 0.1, 1.2, 2.2)
    path = os.path.join(BLOCKOUT, room["id"] + ".obj")
    o.write(path)
    return "assets/models/blockout/%s.obj" % room["id"]


def build_shared_objs(mats):
    mats["pickup_gold"], mats["door_marker"] = [0.95, 0.80, 0.20], [0.95, 0.90, 0.70]
    o = Obj("blockout.mtl")
    o.box("pickup_gold", 0, 0, 0.15, 0.3, 0.3, 0.3)
    o.write(os.path.join(BLOCKOUT, "pickup.obj"))
    o = Obj("blockout.mtl")
    o.box("door_marker", 0, 0, 0.02, 0.9, 0.9, 0.04)
    o.write(os.path.join(BLOCKOUT, "door_marker.obj"))


# --- scene --------------------------------------------------------------------

FIGHT = "sceneState.fight == 1"
# The equipped weapon is a persistent playthrough Variable, so it survives
# room changes. The Baton never runs out, which keeps every fight winnable
# once ammunition is gone, as in the original.
WEAPON = "(variables.weapon or 'handgun')"
OTHER = "(%s == 'baton' and 'handgun' or 'baton')" % WEAPON
SWAP = {"cmd": "SET_GAME_VARIABLE", "name": "weapon", "value": OTHER}
REACH = "(%s == 'baton' and 1.5 or 4)" % WEAPON   # mirrors the skills' realtime.range


def in_fight(expr, default):
    return "(%s and (%s) or %s)" % (FIGHT, expr, default)


PX = "(%s and rt.player.x or sceneState.walkX)" % FIGHT
PY = "(%s and rt.player.y or sceneState.walkY)" % FIGHT


def flags_used(room):
    out = []
    for door in room["doors"]:
        if door.get("needs"):
            out.append(door["needs"])
    for p in room.get("pickups", []):
        out.append("got_" + p["id"])
    return sorted(set(out))


def sv(flag):
    return "f_" + flag


def battle_start(room):
    enc = room["encounter"]
    return {"cmd": "REALTIME_BATTLE_START", "troop": enc["troop"],
            "party": [["sceneState.walkX", "sceneState.walkY"]],
            "enemies": [[enc["at"][0], enc["at"][1]]], "bounds": bounds_of(room)}


def scene_models(room, room_model):
    models = []
    if room.get("corridor"):
        models.append({"id": "room", "model": BACKSTAGE + "corridor.obj", "position": [0, 0, 0], "yaw": 0, "visible": "true"})
    elif room.get("environment"):
        # A Second Gate baked environment package: its atlas already carries the
        # room's lighting, so it is drawn as baked (bakedLighting), never relit.
        models.append({"id": "room", "model": room["environment"], "position": [0, 0, 0], "yaw": 0,
                       "visible": "true", "bakedLighting": True})
    else:
        models.append({"id": "room", "model": room_model, "position": [0, 0, 0], "yaw": 0, "visible": "true"})
    for door in room["doors"]:
        x, y = door_point(room, door)
        models.append({"id": "door_" + door["id"], "model": "assets/models/blockout/door_marker.obj",
                       "position": [x, y, 0], "yaw": 0, "visible": "sceneState.near == %s" % q(door["id"])})
    for p in room.get("pickups", []):
        models.append({"id": "pickup_" + p["id"], "model": BACKSTAGE + "spark.obj", "scale": [0.35, 0.35, 0.35],
                       "position": [p["at"][0], p["at"][1], 0.15], "yaw": "sceneState.gait * 0 + time_spin",
                       "visible": "sceneState.%s == 0" % sv("got_" + p["id"])})
    walking = "sceneState.moving == 1"
    models += [
        {"id": "aya_shadow", "model": BACKSTAGE + "contact_shadow.obj", "position": [PX, PY, 0], "yaw": 0, "visible": "true", "scale": [0.55, 0.55, 1]},
        {"id": "aya", "model": AYA + "aya_idle.obj", "position": [PX, PY, 0], "yaw": "sceneState.aim",
         "visible": "(%s and rt.outcome ~= 'defeat' and rt.actAge >= 12 and (sceneState.moving == 0 or sceneState.ui > 0 or rt.outcome ~= '')) or (sceneState.fight == 0 and (sceneState.moving == 0 or sceneState.ui > 0))" % FIGHT},
    ]
    # Eight-frame walk cycle (tools/build_aya.py); gait advances 10 rad/s.
    for k in range(8):
        models.append({"id": "aya_walk_%d" % k, "model": AYA + "aya_walk_%d.obj" % k, "position": [PX, PY, 0],
                       "yaw": "sceneState.aim",
                       "visible": "sceneState.ui == 0 and %s and floor(sceneState.gait / 6.283185 * 8) %% 8 == %d"
                                  " and (sceneState.fight == 0 or rt.outcome == '')" % (walking, k)})
    if "encounter" in room:
        enemy = room["encounter"]["enemy"]
        ex, ey = "rt.enemy.x", "rt.enemy.y"
        tint = in_fight("rt.hitAge < 12 and not rt.hitOnPlayer and .4 or 1", 1)
        models += [
            {"id": "aya_down", "model": AYA + "aya_down.obj", "position": [PX, PY, 0], "yaw": "sceneState.aim",
             "visible": in_fight("rt.outcome == 'defeat'", "false")},
            {"id": "aya_recoil", "model": AYA + "aya_recoil.obj", "position": [PX, PY, 0], "yaw": "sceneState.aim",
             "visible": in_fight("rt.outcome ~= 'defeat' and rt.actAge < 12", "false")},
            {"id": "range_ground", "model": BACKSTAGE + "range_ground.obj", "position": [PX, PY, 0.03], "yaw": 0,
             "visible": "sceneState.ui == 2", "scale": [REACH, REACH, 1]},
            {"id": "muzzle", "model": BACKSTAGE + "spark.obj",
             "position": [PX + "+sin(sceneState.aim)*.72", PY + "-cos(sceneState.aim)*.72", 1.47], "yaw": 0,
             "visible": in_fight("rt.actAge < 12", "false")},
        ]
        epos = [in_fight(ex, 0), in_fight(ey, 0), 0]
        live = "rt.outcome ~= 'victory'"
        if enemy == "rat":
            models += [
                {"id": "enemy_shadow", "model": BACKSTAGE + "contact_shadow.obj", "position": epos, "yaw": 0,
                 "visible": in_fight(live, "false"), "scale": [1.5, 2.6, 1]},
                {"id": "rat", "model": BACKSTAGE + "rat.obj", "position": epos, "yaw": "sceneState.ratAim",
                 "visible": in_fight("(not rt.enemy.windup and rt.enemy.strikeAge >= 20) and " + live, "false"), "tint": [1, tint, tint]},
                {"id": "rat_windup", "model": BACKSTAGE + "rat_windup.obj", "position": epos, "yaw": "sceneState.ratAim",
                 "visible": in_fight("rt.enemy.windup and " + live, "false"), "tint": [1, tint, tint]},
                {"id": "rat_lunge", "model": BACKSTAGE + "rat_lunge.obj", "position": epos, "yaw": "sceneState.ratAim",
                 "visible": in_fight("(not rt.enemy.windup and rt.enemy.strikeAge < 20) and " + live, "false"), "tint": [1, tint, tint]},
            ]
        else:
            # Authored boss poses (tools/build_bosses.py): idle, and the wind-up
            # telegraph swapped in while the attack charges.
            models += [
                {"id": "enemy_shadow", "model": BACKSTAGE + "contact_shadow.obj", "position": epos, "yaw": 0,
                 "visible": in_fight(live, "false"), "scale": [1.6, 1.6, 1]},
                {"id": "enemy", "model": BOSSES + enemy + "_idle.obj", "position": epos, "yaw": "sceneState.ratAim",
                 "visible": in_fight("not rt.enemy.windup and " + live, "false"), "tint": [1, tint, tint]},
                {"id": "enemy_windup", "model": BOSSES + enemy + "_windup.obj", "position": epos, "yaw": "sceneState.ratAim",
                 "visible": in_fight("rt.enemy.windup and " + live, "false"), "tint": [1, tint, tint]},
            ]
        models += [
            {"id": "target", "model": BACKSTAGE + "target_cursor.obj", "position": [epos[0], epos[1], 1.1], "yaw": 0,
             "visible": "sceneState.ui == 2"},
        ]
        for i in range(3):
            models.append({"id": "fire%d" % i, "model": BACKSTAGE + "spark.obj",
                           "position": [in_fight("rt.fire[%d].x" % (i + 1), 0), in_fight("rt.fire[%d].y" % (i + 1), 0), 0.35],
                           "yaw": 0, "visible": in_fight("rt.fire[%d].live" % (i + 1), "false"), "scale": [1.8, 1.8, 2.8]})
    # the pickup spin above is decorative; keep the formula free of unknown names
    for m in models:
        if isinstance(m.get("yaw"), str) and "time_spin" in m["yaw"]:
            m["yaw"] = "sceneState.gait * 0.25"
    return models


def camera_of(room):
    """A room lists one or more fixed "views", composed from the original's
    shots. Each view has a "when" condition on Aya's x/y (the last is the
    fallback) and the camera hard-cuts between them. A view can also scroll,
    as the original's oversized backgrounds do:
      "track": {"axis": "y", "range": [a, b]} with position/target given as
          {"from": [...], "to": [...]} glides between two framings as Aya
          walks from a to b (the tall-background tilt along a room's depth);
      "pan": k slides camera and target sideways by k * Aya's x (the
          wide-background pan)."""
    if room.get("views"):
        views = room["views"]
        fov = views[0]["fov"]
        assert all(v["fov"] == fov for v in views), room["id"] + ": views share one fov"
        coord = {"x": PX, "y": PY}

        def cond(text):
            return "(" + re.sub(r"\by\b", PY, re.sub(r"\bx\b", PX, text)) + ")"

        def component(v, key, axis):
            spec = v[key]
            if isinstance(spec, dict):
                a, b = v["track"]["range"]
                t = "clamp((%s - %g) / %g, 0, 1)" % (coord[v["track"]["axis"]], a, b - a)
                lo, hi = spec["from"][axis], spec["to"][axis]
                expr = "(%g + %g * %s)" % (lo, hi - lo, t) if hi != lo else "%g" % lo
            else:
                expr = "%g" % spec[axis]
            if axis == 0 and v.get("pan"):
                expr = "(%s + %g * %s)" % (expr, v["pan"], PX)
            return expr

        def pick(key, axis):
            expr = component(views[-1], key, axis)
            for v in reversed(views[:-1]):
                expr = "(%s and %s or %s)" % (cond(v["when"]), component(v, key, axis), expr)
            return expr
        return {"position": [pick("position", i) for i in range(3)],
                "target": [pick("target", i) for i in range(3)], "fov": fov}
    if room.get("camera"):
        return dict(room["camera"])
    if room.get("corridor"):
        return dict(CORRIDOR_CAMERA)
    w, d = room_dims(room)
    return {"position": [0, -d * 0.55 - 1.5, d * 0.85 + 2.6], "target": [0, d * 0.48, 0.4], "fov": 44}


def windows(room, room_model):
    world = {"id": "world", "rect": {"x": "-surface.originX", "y": "-surface.originY", "w": "surface.width", "h": "surface.height"},
             "style": "modelScene", "chrome": "none",
             "viewport": {"camera": camera_of(room), "background": [0.025, 0.025, 0.018],
                          "models": scene_models(room, room_model)},
             "content": []}
    if "encounter" in room:
        world["viewport"]["labels"] = [{
            "value": "rt.missAge < rt.hitAge and 'MISS' or rt.hitAmount",
            "position": [in_fight("rt.hitOnPlayer and rt.missAge >= rt.hitAge and rt.player.x or rt.enemy.x", 0),
                         in_fight("rt.hitOnPlayer and rt.missAge >= rt.hitAge and rt.player.y or rt.enemy.y", 0),
                         in_fight("1.2 + min(rt.hitAge, rt.missAge) / 60 * 1.2", 0)],
            "visible": in_fight("min(rt.hitAge, rt.missAge) < 48", "false"), "color": [1, 1, 0.88, 1]}]
    out = [world]
    if "encounter" in room:
        hud = FIGHT
        out += [
            {"id": "combat_hud", "rect": {"x": "1.5 - surface.originX", "y": 1, "w": 13, "h": 4.5}, "style": "panel", "chrome": "overlay",
             "visible": hud, "content": [
                {"type": "gauge", "x": 0.7, "y": 0.65, "width": 8.5, "height": 0.4, "labelPlacement": "right", "label": "AT",
                 "value": "rt.player.at", "max": "100", "fill": [0.08, "rt.player.at >= 100 and .45+.4*abs(sin(sceneState.gait)) or .7", 0.85],
                 "color": [0.04, 0.07, 0.06]},
                {"type": "gauge", "x": 0.7, "y": 3.5, "width": 8.5, "height": 0.4, "labelPlacement": "right", "label": "PE",
                 "value": "rt.player.res.pe", "max": "100", "fill": [0.02, 0.85, 0.15], "color": [0.04, 0.07, 0.06]}]},
            {"id": "hp", "rect": {"x": "3.2 - surface.originX", "y": 2.3, "w": 7, "h": 1.5}, "style": "panel", "chrome": "none",
             "visible": hud, "content": [{"type": "text", "text": "{rt.player.hp}/{rt.player.maxHp}"}]},
            {"id": "hp_label", "rect": {"x": "10 - surface.originX", "y": 2.3, "w": 3.5, "h": 1.5}, "style": "panel", "chrome": "none",
             "visible": hud, "content": [{"type": "text", "text": "HP"}]},
            {"id": "command", "rect": {"x": "1 - surface.originX", "y": 7, "w": 13, "h": 8}, "style": "panel", "chrome": "overlay",
             "visible": "sceneState.ui == 1", "content": [{"type": "text", "text":
                "{sceneState.choice == 0 and '> Attack' or '  Attack'}\n{sceneState.choice == 1 and '> P. Energy' or '  P. Energy'}\n"
                "{sceneState.choice == 2 and '> Item' or '  Item'}\n{sceneState.choice == 3 and '> Escape' or '  Escape'}"}]},
            {"id": "target_info", "rect": {"x": "surface.width - surface.originX - 13", "y": 13, "w": 12, "h": 5}, "style": "panel",
             "chrome": "overlay", "visible": "sceneState.ui == 2",
             "content": [{"type": "text", "text": "{" + WEAPON + " == 'baton' and 'BATON' or 'M84F'}\n"
                          "{" + WEAPON + " == 'baton' and 'NO AMMO' or 'BULLETS ' .. (rt.items.handgun_ammo or 0)}\nTARGET   1"}]},
            {"id": "pe_menu", "rect": {"x": "1 - surface.originX", "y": 7, "w": 15, "h": 5}, "style": "panel", "chrome": "overlay",
             "visible": "sceneState.ui == 3", "content": [{"type": "text", "text": "> Heal 1\nRecover 30 HP\nPE cost 30"}]},
            {"id": "item_menu", "rect": {"x": "1 - surface.originX", "y": 7, "w": 17, "h": 5}, "style": "panel", "chrome": "overlay",
             "visible": "sceneState.ui == 4", "content": [{"type": "text", "text":
                "{sceneState.choice == 0 and '>' or ' '} Medicine x{(rt.items.medicine or 0)}\n"
                "{sceneState.choice == 1 and '>' or ' '} Equip {" + OTHER + " == 'baton' and 'Baton' or 'Handgun'}"}]},
            {"id": "result", "rect": {"x": 6, "y": 9, "w": 21, "h": 6}, "style": "panel", "chrome": "overlay",
             "visible": in_fight("rt.outcome == 'victory'", "false") + " and sceneState.ui ~= 9",
             "content": [{"type": "text", "text": "Battle over\n> Obtain all"}]},
            {"id": "loss", "rect": {"x": 7, "y": 10, "w": 20, "h": 5}, "style": "panel", "chrome": "overlay",
             "visible": in_fight("rt.outcome == 'defeat'", "false"), "content": [{"type": "text", "text": "Aya has fallen\nEnter: retry"}]},
        ]
    out += [
        {"id": "card", "rect": {"x": "4 - surface.originX", "y": 7, "w": "surface.width - 8", "h": 14}, "style": "panel",
         "chrome": "overlay", "visible": "sceneState.ui == 9", "content": [{"type": "text", "text": "{sceneState.card}"}]},
        {"id": "weapon", "rect": {"x": "surface.width - surface.originX - 15", "y": 1, "w": 14, "h": 2}, "style": "panel",
         "chrome": "none", "visible": "sceneState.ui ~= 9",
         "content": [{"type": "text", "text": "{" + WEAPON + " == 'baton' and 'Baton' or 'Handgun'}{sceneState.fight == 0 and '  [X]' or ''}"}]},
        {"id": "feedback", "rect": {"x": "1 - surface.originX", "y": 27.5, "w": 34, "h": 2}, "style": "panel", "chrome": "none",
         "visible": "sceneState.ui ~= 9",
         "content": [{"type": "text", "text": "{%s}" % in_fight("rt.refusalAge < 90 and rt.refusal or sceneState.status", "sceneState.status")}]},
    ]
    return out


def on_enter(room, spawn):
    hooks = [
        {"cmd": "COMMENT", "text": "Generated from tools/chapter/rooms.json by build_chapter.py; edit the table, not this file."},
        setv(ui=0, choice=0, menuHeld="false", gait=0, moving=0, dx=0, dy=0, range=4, aim=0, ratAim=0,
             fight=0, near="''", card="''", status=q(room["name"]),
             walkX="sceneState.walkX or %s" % spawn[0], walkY="sceneState.walkY or %s" % spawn[1]),
        setv(entryX="sceneState.walkX", entryY="sceneState.walkY"),
    ]
    for flag in flags_used(room):
        hooks.append(setv(**{sv(flag): 0}))
        hooks.append(iff("flag:" + flag, [setv(**{sv(flag): 1})]))
    card = room.get("card")
    if card:
        show = [setv(card=q(card["text"]))]
        if card.get("once"):
            hooks.append(iff("flag:" + card["once"], [], [{"cmd": "SET_FLAG", "flag": card["once"], "value": True}] + show))
        else:
            hooks += show
    visit = room.get("visitCard")
    if visit:
        seen = "visited_" + room["id"] + "_" + visit["flag"]
        grant = [{"cmd": "SET_FLAG", "flag": seen, "value": True}, setv(card=q(visit["text"]))]
        if visit.get("heal"):
            grant.append({"cmd": "RECOVER_PARTY"})
        if visit.get("item"):
            grant.append({"cmd": "CHANGE_ITEM", "item": visit["item"][0], "count": visit["item"][1]})
        hooks.append(iff("flag:" + visit["flag"], [iff("flag:" + seen, [], [iff("sceneState.card == ''", grant)])]))
    if "encounter" in room:
        enc = room["encounter"]
        hooks.append(iff("flag:" + enc["cleared"], [], [setv(fight=1), battle_start(room)]))
    hooks.append(setv(ui="sceneState.card ~= '' and 9 or 0"))
    if room.get("encounter"):
        hooks.append(iff(FIGHT, [{"cmd": "REALTIME_BATTLE_PAUSE", "paused": "sceneState.ui > 0"}]))
    return hooks


def on_frame(room):
    b = bounds_of(room)
    move = [
        setv(dx="sceneState.ui == 0 and ((sceneState.input.RIGHT and 1 or 0) - (sceneState.input.LEFT and 1 or 0)) or 0",
             dy="sceneState.ui == 0 and ((sceneState.input.UP and 1 or 0) - (sceneState.input.DOWN and 1 or 0)) or 0"),
        setv(moving="(sceneState.dx ~= 0 or sceneState.dy ~= 0) and 1 or 0"),
        iff("sceneState.moving == 1", [setv(gait="sceneState.gait + time.dt * 10",
                                            aim="atan2(sceneState.dx, -sceneState.dy)")]),
    ]
    explore = move + [
        setv(walkX="max(%s, min(%s, sceneState.walkX + sceneState.dx * %s))" % (b["minX"], b["maxX"], WALK_SPEED),
             walkY="max(%s, min(%s, sceneState.walkY + sceneState.dy * %s))" % (b["minY"], b["maxY"], WALK_SPEED)),
        iff("sceneState.input.X and not sceneState.menuHeld and sceneState.ui == 0", [SWAP]),
        setv(menuHeld="sceneState.input.X"),
        setv(near="''", status=q(room["name"])),
    ]
    dist = "((sceneState.walkX - (%s))^2 + (sceneState.walkY - (%s))^2 < %s)"
    for door in room["doors"]:
        x, y = door_point(room, door)
        explore.append(iff(dist % (x, y, NEAR * NEAR), [setv(near=q(door["id"]), status=q("Enter: " + door["label"]))]))
    for p in room.get("pickups", []):
        explore.append(iff("sceneState.%s == 0 and %s" % (sv("got_" + p["id"]), dist % (p["at"][0], p["at"][1], NEAR * NEAR)),
                           [setv(near=q("p:" + p["id"]), status=q("Enter: examine"))]))
    hooks = [{"cmd": "READ_INPUT", "name": "input"}]
    if "encounter" not in room:
        return hooks + explore
    fight = [
        iff("sceneState.input.X and not sceneState.menuHeld and rt.outcome == '' and sceneState.ui ~= 9", [
            iff("sceneState.ui == 0 and rt.player.at >= 100",
                [setv(ui=1, choice=0, status="'Choose a command'")],
                [iff("sceneState.ui > 0", [setv(ui=0, status="''")])])]),
        setv(menuHeld="sceneState.input.X"),
    ] + move + [
        setv(moving="sceneState.moving == 1 and rt.outcome == '' and 1 or 0"),
        {"cmd": "REALTIME_BATTLE_PAUSE", "paused": "sceneState.ui > 0"},
        {"cmd": "REALTIME_BATTLE_STEP", "dx": "sceneState.dx", "dy": "sceneState.dy"},
        iff("sceneState.moving == 0", [setv(aim="atan2(rt.enemy.x - rt.player.x, rt.player.y - rt.enemy.y)")]),
        setv(ratAim="atan2(rt.player.x - rt.enemy.x, rt.enemy.y - rt.player.y)"),
    ]
    return hooks + [iff(FIGHT, fight, explore)]


def fight_select(room):
    enc = room["encounter"]
    menu = iff("sceneState.ui == 0", [
        iff("rt.player.at >= 100", [setv(ui=2, status="'Choose target'")])], [
        iff("sceneState.ui == 2", [
            iff(WEAPON + " == 'baton'",
                [{"cmd": "REALTIME_BATTLE_COMMAND", "kind": "skill", "id": "baton_strike", "target": "enemy"}],
                [{"cmd": "REALTIME_BATTLE_COMMAND", "kind": "skill", "id": "handgun_shot", "target": "enemy"}]),
            setv(ui=0, status="''")], [
            iff("sceneState.ui == 1", [
                iff("sceneState.choice == 0", [setv(ui=2, status="'Choose target'")]),
                iff("sceneState.choice == 1", [setv(ui=3)]),
                iff("sceneState.choice == 2", [setv(ui=4, choice=0)]),
                iff("sceneState.choice == 3", [{"cmd": "REALTIME_BATTLE_COMMAND", "kind": "skill", "id": "escape", "target": "self"}, setv(ui=0)]),
            ], [
                iff("sceneState.ui == 3", [{"cmd": "REALTIME_BATTLE_COMMAND", "kind": "skill", "id": "heal1", "target": "self"}, setv(ui=0, status="''")], [
                    iff("sceneState.ui == 4", [iff("sceneState.choice == 0",
                        [{"cmd": "REALTIME_BATTLE_COMMAND", "kind": "item", "id": "medicine", "target": "self"}],
                        [SWAP]), setv(ui=0, status="''")])])])])])
    leave = [setv(walkX="rt.player.x", walkY="rt.player.y"), {"cmd": "REALTIME_BATTLE_END"}, setv(fight=0, ui=0)]
    return iff("rt.outcome == 'victory'", [
        {"cmd": "SET_FLAG", "flag": enc["cleared"], "value": True}] + leave + [setv(card=q(enc["after"]), ui=9)], [
        iff("rt.outcome == 'defeat'", [
            {"cmd": "COMMENT", "text": "Rough-chapter retry: restore Aya and restart this room's fight where she entered."},
            {"cmd": "REALTIME_BATTLE_END"}, {"cmd": "RECOVER_PARTY"},
            setv(walkX="sceneState.entryX", walkY="sceneState.entryY", ui=0), battle_start(room)], [
            iff("rt.outcome == 'escaped'", leave + [setv(status="'Escaped. It is still here.'")], [menu])])])


def on_select(room):
    card = room.get("card") or {}
    dismiss = [setv(card="''", ui=0)]
    if card.get("then"):
        assert card["then"] == "title", "a card can only end the chapter (pop back to the title)"
        dismiss.append({"cmd": "SCENE_EVENT", "kind": "pop"})
    explore = []
    for door in room["doors"]:
        go = [{"cmd": "SCENE_EVENT", "kind": "goto", "scene": "day1_" + door["to"],
               "sceneState": [{"name": "walkX", "value": door["spawn"][0]}, {"name": "walkY", "value": door["spawn"][1]}]}]
        if door.get("needs"):
            go = [iff("flag:" + door["needs"], go, [setv(card=q(door["lockedText"]), ui=9)])]
        explore.append(iff("sceneState.near == %s" % q(door["id"]), go))
    for p in room.get("pickups", []):
        got = [{"cmd": "SET_FLAG", "flag": "got_" + p["id"], "value": True}, setv(**{sv("got_" + p["id"]): 1})]
        if p.get("item"):
            got.append({"cmd": "CHANGE_ITEM", "item": p["item"][0], "count": p["item"][1]})
        if p.get("flag"):
            got.append({"cmd": "SET_FLAG", "flag": p["flag"], "value": True})
        got.append(setv(card=q(p["text"]), ui=9))
        explore.append(iff("sceneState.near == %s" % q("p:" + p["id"]), got))
    body = explore
    if "encounter" in room:
        body = [iff(FIGHT, [fight_select(room)], explore)]
    return [iff("sceneState.ui == 9", dismiss, body)]


def on_cancel(room):
    if "encounter" not in room:
        return []
    return [iff(FIGHT + " and sceneState.ui > 0 and sceneState.ui < 9 and rt.outcome == ''", [setv(ui=0, status="''")])]


def scene(room, room_model, spawn):
    menu_move = lambda step: [iff("sceneState.ui == 1", [setv(choice="(sceneState.choice+%d)%%4" % step)]),
                              iff("sceneState.ui == 4", [setv(choice="(sceneState.choice+1)%2")])]
    return {
        "id": "day1_" + room["id"], "name": room["name"], "kind": "menu", "draw": "windows",
        "update": {"mode": "fixed", "step": 1 / 60, "maxCatchUp": 60},
        "windows": windows(room, room_model),
        "hooks": {"on_enter": on_enter(room, spawn), "on_frame": on_frame(room), "on_select": on_select(room),
                  "on_cancel": on_cancel(room), "on_up": menu_move(3), "on_down": menu_move(1), "on_left": [], "on_right": []},
    }


def main():
    table = json.load(open(os.path.join(HERE, "rooms.json"), encoding="utf-8"))
    os.makedirs(BLOCKOUT, exist_ok=True)
    mats = {}
    build_shared_objs(mats)
    ids = {r["id"] for r in table["rooms"]}
    written = []
    for room in table["rooms"]:
        for door in room["doors"]:
            assert door["to"] in ids, "%s: door %s goes to unknown room %s" % (room["id"], door["id"], door["to"])
        model = None if room.get("corridor") else build_room_obj(room, mats)
        spawn = [table["start"]["x"], table["start"]["y"]] if room["id"] == table["start"]["room"] else [0, 1]
        data = scene(room, model, spawn)
        name = "day1_%s.json" % room["id"]
        with open(os.path.join(SCENES, name), "w", encoding="utf-8", newline="\n") as fh:
            json.dump(data, fh, indent=2)
            fh.write("\n")
        written.append(name)
    write_mtl(os.path.join(BLOCKOUT, "blockout.mtl"), mats)
    index_path = os.path.join(SCENES, "index.json")
    index = json.load(open(index_path, encoding="utf-8"))
    keep = [f for f in index["files"] if not f.startswith("day1_")]
    index["files"] = keep + written
    with open(index_path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(index, fh, indent=2)
        fh.write("\n")
    print("wrote %d room scenes and blockout geometry" % len(written))


if __name__ == "__main__":
    main()
