// Deterministic low-poly completion pass for item models that still used the
// runtime question-mark fallback.  The geometry is deliberately authored from
// reusable silhouettes so variants remain art-directable and reproducible.
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'assets', 'models', 'items');
const MTL = 'item_complete_library.mtl';
const materials = {
  wrought_iron:[.157,.157,.149], ritual_gold:[.569,.467,.235], oxidized_bronze:[.337,.337,.267],
  dark_wood:[.275,.188,.133], aged_cloth:[.439,.353,.275], smoked_glass:[.196,.239,.235],
  wet_residue:[.196,.275,.196], bone:[.745,.698,.569], wax:[.608,.494,.275], crystal:[.353,.510,.588],
  old_limestone:[.561,.537,.467], rough_limestone:[.494,.467,.396]
};
class Mesh {
  constructor(name){this.name=name;this.vs=[];this.fs=[];}
  v(p){this.vs.push(p.map(n=>+n.toFixed(6)));return this.vs.length;}
  tri(m,a,b,c){this.fs.push([m,[a,b,c]]);}
  quad(m,a,b,c,d){this.tri(m,a,b,c);this.tri(m,a,c,d);}
  box(c,s,m){let [x,y,z]=c,[a,b,d]=s.map(n=>n/2),p=[[x-a,y-b,z-d],[x+a,y-b,z-d],[x+a,y+b,z-d],[x-a,y+b,z-d],[x-a,y-b,z+d],[x+a,y-b,z+d],[x+a,y+b,z+d],[x-a,y+b,z+d]],i=p.map(q=>this.v(q));[[0,3,2,1],[4,5,6,7],[0,1,5,4],[3,7,6,2],[0,4,7,3],[1,2,6,5]].forEach(q=>this.quad(m,...q.map(k=>i[k])));}
  prism(a,b,r0,r1,s,m){let axis=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],len=Math.hypot(...axis);axis=axis.map(n=>n/len);let u=[-axis[1],axis[0],0],ul=Math.hypot(...u)||1;u=u.map(n=>n/ul);let v=[axis[1]*u[2]-axis[2]*u[1],axis[2]*u[0]-axis[0]*u[2],axis[0]*u[1]-axis[1]*u[0]],rings=[];for(const [p,r] of [[a,r0],[b,r1]]){let ring=[];for(let k=0;k<s;k++){let t=2*Math.PI*k/s;ring.push(this.v([p[0]+r*(u[0]*Math.cos(t)+v[0]*Math.sin(t)),p[1]+r*(u[1]*Math.cos(t)+v[1]*Math.sin(t)),p[2]+r*(u[2]*Math.cos(t)+v[2]*Math.sin(t))]));}rings.push(ring);}let c0=this.v(a),c1=this.v(b);for(let k=0;k<s;k++){let j=(k+1)%s;this.tri(m,c0,rings[0][j],rings[0][k]);this.tri(m,c1,rings[1][k],rings[1][j]);this.quad(m,rings[0][k],rings[0][j],rings[1][j],rings[1][k]);}}
  diamond(c,r,h,m,s=6){let ring=[];for(let k=0;k<s;k++){let t=2*Math.PI*k/s;ring.push(this.v([c[0]+r*Math.cos(t),c[1],c[2]+r*Math.sin(t)]));}let a=this.v([c[0],c[1]+h/2,c[2]]),b=this.v([c[0],c[1]-h/2,c[2]]);for(let k=0;k<s;k++){let j=(k+1)%s;this.tri(m,a,ring[k],ring[j]);this.tri(m,b,ring[j],ring[k]);}}
  extrude(points,z0,z1,m){let lo=points.map(p=>this.v([p[0],p[1],z0])),hi=points.map(p=>this.v([p[0],p[1],z1]));for(let k=1;k<points.length-1;k++){this.tri(m,lo[0],lo[k+1],lo[k]);this.tri(m,hi[0],hi[k],hi[k+1]);}for(let k=0;k<points.length;k++){let j=(k+1)%points.length;this.quad(m,lo[k],lo[j],hi[j],hi[k]);}}
  center(){let lo=[0,1,2].map(i=>Math.min(...this.vs.map(p=>p[i]))),hi=[0,1,2].map(i=>Math.max(...this.vs.map(p=>p[i]))),c=lo.map((n,i)=>(n+hi[i])/2);this.vs=this.vs.map(p=>p.map((n,i)=>n-c[i]));}
}
function sword(m,n,kind){let L=kind==='knife'?2.25:kind==='great'?4.0:3.15,w=kind==='knife'?.19:kind==='great'?.34:.25,g=kind==='spear'?.72:.78;let y0=-L/2+.55,y1=L/2-.34,curve=n.includes('Coral')?.12:n.includes('Air')?-.08:0;let pts=[[-w,y0],[-w-.06,y0+.3],[-w*.75+curve,y1],[curve,y1+.34],[w*.75+curve,y1],[w+.06,y0+.3],[w,y0]];m.extrude(pts,-.065,.065,n.includes('Glass')?'smoked_glass':'wrought_iron');m.box([0,y0-.08,0],[g,.14,.22],'ritual_gold');m.prism([0,y0-.14,0],[0,y0-.68,0],.1,.07,6,'dark_wood');m.diamond([0,y0-.76,0],.14,.18,'ritual_gold',4);if(n.includes('Rune'))for(let y=.1;y<.9;y+=.3)m.box([0,y,.08],[.09,.12,.03],'crystal');}
function build(item){let n=item.name,id=item.id,m=new Mesh(n), lower=n.toLowerCase();
  if(item.type==='equipment' && id>=85&&id<=112){let cloth=lower.includes('robe')||lower.includes('cloak')||lower.includes('coat')||lower.includes('vestment')?'aged_cloth':lower.includes('slime')?'wet_residue':'wrought_iron';let accent=lower.includes('dragon')||lower.includes('flame')||lower.includes('hero')?'ritual_gold':lower.includes('bone')||lower.includes('cocoon')?'bone':'oxidized_bronze';m.extrude([[-.48,-.72],[-.62,-.3],[-.42,.62],[0,.82],[.42,.62],[.62,-.3],[.48,-.72]],-.25,.25,cloth);m.box([0,.25,.28],[.42,.55,.16],accent);m.box([-.68,-.2,0],[.18,.68,.2],cloth);m.box([.68,-.2,0],[.18,.68,.2],cloth);if(lower.includes('mask'))m.box([0,.2,.36],[.5,.36,.2],'smoked_glass');}
  else if(item.type==='equipment' && (id<=84||lower.includes('sword')||lower.includes('knife')||lower.includes('blade')||lower.includes('staff')||lower.includes('spear')||lower.includes('sickle')||lower.includes('cleaver')||lower.includes('club')||lower.includes('fang')||lower.includes('bunker')||lower.includes('executioner'))){if(lower.includes('staff')||lower.includes('wand')){m.prism([0,-1.55,0],[0,1.05,0],.11,.08,7,'dark_wood');m.diamond([0,1.38,0],.3,.5,lower.includes('healing')?'crystal':'ritual_gold',7);if(lower.includes('ether')||lower.includes('sage'))m.box([0,1.12,.05],[.6,.12,.14],'crystal');}else if(lower.includes('spear')||lower.includes('hook')){m.prism([0,-1.65,0],[0,1.25,0],.09,.07,6,'dark_wood');m.extrude([[-.28,1.05],[-.1,1.75],[0,2.0],[.1,1.75],[.28,1.05],[0,1.25]],-.08,.08,'wrought_iron');if(lower.includes('barbed')||lower.includes('hook'))m.diamond([0,1.38,.1],.16,.22,'ritual_gold',5);}else if(lower.includes('sickle')){m.prism([0,-1.5,0],[0,.55,0],.1,.07,6,'dark_wood');m.extrude([[-.08,.45],[-.5,.75],[-.62,1.1],[-.35,1.42],[.02,1.12],[.18,.75]],-.08,.08,'wrought_iron');}else if(lower.includes('club')||lower.includes('fang')){m.prism([0,-1.4,0],[0,.85,0],.16,.12,7,lower.includes('bone')?'bone':'dark_wood');m.diamond([0,1.05,0],.3,.6,lower.includes('bone')?'bone':'wrought_iron',6);}else if(lower.includes('bunker')){m.box([0,-.3,0],[.36,2.2,.36],'wrought_iron');m.box([0,.8,.24],[.48,.3,.48],'ritual_gold');}else if(lower.includes('cleaver')){m.extrude([[-.48,-.5],[-.48,.65],[-.15,1.0],[.48,.72],[.42,-.5]],-.09,.09,'wrought_iron');m.prism([0,-.85,0],[0,-.25,0],.1,.08,6,'dark_wood');}else sword(m,n,lower.includes('knife')?'knife':lower.includes('great')||lower.includes('executioner')?'great':'sword');}
  else if(item.type==='equipment' && (id>=113||lower.includes('ring')||lower.includes('bell')||lower.includes('pendant')||lower.includes('coin')||lower.includes('badge')||lower.includes('feather')||lower.includes('scale')||lower.includes('ribbon')||lower.includes('cape')||lower.includes('glove')||lower.includes('shoe')||lower.includes('harness'))){if(lower.includes('ring')){m.prism([0,0,0],[0,.18,0],.42,.42,8,'ritual_gold');m.diamond([0,.22,0],.18,.22,lower.includes('ruby')||lower.includes('sapphire')||lower.includes('emerald')||lower.includes('onyx')?'crystal':'ritual_gold',6);}else if(lower.includes('bell')){m.prism([0,-.25,0],[0,.25,0],.25,.18,8,'oxidized_bronze');m.box([0,-.36,0],[.12,.16,.12],'wrought_iron');}else if(lower.includes('feather')||lower.includes('scale')){m.diamond([0,0,0],.45,.9,lower.includes('scale')?'bone':'aged_cloth',5);}else if(lower.includes('glass')){m.prism([-.22,0,0],[-.22,.02,0],.22,.22,8,'smoked_glass');m.prism([.22,0,0],[.22,.02,0],.22,.22,8,'smoked_glass');m.box([0,.02,0],[.12,.08,.08],'ritual_gold');}else if(lower.includes('shoe')||lower.includes('glove')||lower.includes('harness')||lower.includes('saddle')){m.box([0,-.1,0],[.9,.38,.52],'aged_cloth');m.box([0,.12,.25],[.55,.12,.1],'ritual_gold');}else if(lower.includes('cape')||lower.includes('ribbon')||lower.includes('belt')||lower.includes('apron')||lower.includes('hat')){m.extrude([[-.55,-.35],[-.55,.3],[0,.6],[.55,.3],[.55,-.35]],-.12,.12,'aged_cloth');m.box([0,.05,.16],[.5,.12,.12],'ritual_gold');}else if(lower.includes('shield')||lower.includes('buckler')){m.diamond([0,0,0],.5,.18,'wrought_iron',8);m.box([0,0,.16],[.16,.44,.1],'ritual_gold');}else{m.box([0,0,0],[.72,.18,.42],lower.includes('glass')?'smoked_glass':'ritual_gold');m.diamond([0,.18,.08],.22,.28,lower.includes('shard')?'crystal':'aged_cloth',6);}}
  else if(item.type==='consumable'){if(lower.includes('food')||['pão','coxinha','feijoada','moqueca','congee','onigiri','tamagoyaki','natto','mooncake','mochi','daifuku','curry','stew','sushi','ramen','pizza','risotto','tempura','kimchi'].some(x=>lower.includes(x))){m.box([0,-.1,0],[.75,.3,.58],lower.includes('slime')?'wet_residue':'aged_cloth');m.diamond([0,.18,0],.27,.32,lower.includes('mandrake')?'bone':'wax',6);}else if(lower.includes('incense')||lower.includes('lamp')){m.prism([0,-.35,0], [0,.4,0],.28,.18,8,'wax');m.diamond([0,.65,0],.18,.32,'wrought_iron',6);}else if(lower.includes('bomb')){m.diamond([0,0,0],.38,.62,'wrought_iron',8);m.prism([0,.28,0],[0,.6,0],.08,.04,6,'wax');}else if(lower.includes('clock')||lower.includes('bell')||lower.includes('salt')||lower.includes('nut')){m.prism([0,-.35,0],[0,.35,0],.32,.28,8,'oxidized_bronze');m.box([0,.44,0],[.2,.18,.2],lower.includes('clock')?'ritual_gold':'wax');m.diamond([0,.62,0],.16,.2,'crystal',6);}else{let r=lower.includes('drop')?.22:lower.includes('flask')?.3:.25; m.prism([0,-.52,0],[0,.48,0],r,r*.78,8,lower.includes('ether')?'crystal':'smoked_glass');m.prism([0,.42,0],[0,.7,0],.12,.1,6,'ritual_gold');m.box([0,-.52,0],[r*1.8,.1,r*1.8],'aged_cloth');}}
  else {m.box([0,-.1,0],[.72,.48,.5],'dark_wood');m.box([0,.2,.28],[.52,.24,.08],'ritual_gold');m.diamond([0,.52,0],.2,.3,'crystal',6);}
  m.center();return m;
}
function writeMtl(){let s='';for(const [id,c] of Object.entries(materials))s+=`newmtl ${id}\nKd ${c.map(n=>n.toFixed(3)).join(' ')}\n\n`;fs.writeFileSync(path.join(OUT,MTL),s);}
function writeObj(m,item,target=slug(item.name)){let used=[...new Set(m.fs.map(f=>f[0]))],s=`# Second Rite deterministic completion model\n# ${item.name}\nmtllib ${MTL}\no item_${item.id}\ns off\n`;s+=m.vs.map(v=>`v ${v.join(' ')}`).join('\n')+'\n';let cur='';for(const [mat,f] of m.fs){if(mat!==cur){s+=`usemtl ${mat}\n`;cur=mat;}s+=`f ${f.join(' ')}\n`;}fs.writeFileSync(path.join(OUT,`${target}.obj`),s);return {path:`assets/models/items/${target}.obj`,vertices:m.vs.length,triangles:m.fs.length,materials:used};}
function slug(s){return s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function main(){fs.mkdirSync(OUT,{recursive:true});writeMtl();let items=JSON.parse(fs.readFileSync(path.join(ROOT,'data','items.json'))),previous=new Set();try{for(const x of JSON.parse(fs.readFileSync(path.join(ROOT,'tools','asset-production','complete-item-models.json'))).items)previous.add(x.id);}catch(_){}let built=[];for(const item of items){if(item.model&&!previous.has(item.id))continue;let model=writeObj(build(item),item);item.model=model.path;built.push({...model,id:item.id,name:item.name});}const angular=items.find(x=>x.id===2);if(angular)writeObj(build(angular),angular,'bottle_family__angular');fs.writeFileSync(path.join(ROOT,'data','items.json'),JSON.stringify(items,null,2)+'\n');fs.writeFileSync(path.join(ROOT,'tools','asset-production','complete-item-models.json'),JSON.stringify({generatedAt:'2026-08-11',approach:'deterministic family silhouettes',items:built},null,2)+'\n');console.log(JSON.stringify({generated:built.length,items:built},null,2));}
main();
