"""Phase 10: machine-readable material provenance manifest.

Every material used anywhere in the gauntlet, with its source strategy and, for
external assets, the licence and the exact files. No secrets are recorded.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TOWN = ROOT / "projects/hichaukitoden-game/assets/authoring/town"
MATS = TOWN / "materials"
OUT = TOWN / "material-provenance.json"

PROCEDURAL = {
    "procedural:stone_blocks": "Coursed ashlar: warped brick grid, per-block voronoi tone, mortar recess, damp staining, fine grit.",
    "procedural:plaster": "Lime stucco: noise trowel waves, gated sparse distance-to-edge voronoi cracks, fine tooth.",
    "procedural:cobblestone": "Voronoi setts with per-sett tone, moss confined to a narrow joint band, domed height.",
    "procedural:wood": "Brick-grid planks with grain stretched along the board, silvered weathering, dark gaps.",
    "procedural:roof_tile": "Sine barrel profile across rows, per-tile voronoi clay tone, lichen drift.",
    "procedural:metal": "Dark iron with hard-thresholded rust bloom that also kills metallicity and raises roughness.",
    "procedural:window": "Window interior: dark glass by day, warm emissive by night.",
}


def sha256(p: Path):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    entries = []

    for ident, desc in sorted(PROCEDURAL.items()):
        entries.append({
            "id": ident,
            "strategy": "procedural",
            "source": "procedural",
            "description": desc,
            "definedIn": "tools/blender/town_material/proc_materials.py",
            "license": "n/a - generated by project code",
            "externalFiles": [],
        })

    ph = MATS / "polyhaven" / "polyhaven-provenance.json"
    if ph.is_file():
        for a in json.loads(ph.read_text(encoding="utf-8")):
            entries.append({
                "id": "polyhaven:" + a["slug"],
                "strategy": "public-library",
                "source": "Poly Haven",
                "paletteRole": a["paletteRole"],
                "displayName": a.get("displayName"),
                "authors": a.get("authors"),
                "sourceUrl": a["assetPage"],
                "license": a["license"],
                "licenseVerifiedAt": a["licenseVerifiedAt"],
                "licenseVerifiedOn": a["licenseVerifiedOn"],
                "commercialUse": a["commercialUse"],
                "redistribution": a["redistribution"],
                "attributionRequired": a["attributionRequired"],
                "resolution": a["resolution"],
                "externalFiles": [
                    {"map": k, "file": "materials/polyhaven/%s/%s" % (a["slug"], v["file"]),
                     "sourceUrl": v["sourceUrl"], "sha256": v["sha256"], "bytes": v["bytes"]}
                    for k, v in sorted(a["maps"].items())],
                "usedIn": "facade / ground / roof / timber / metal field textures",
            })

    gen_dir = MATS / "generated"
    for meta in sorted(gen_dir.glob("gen_*.json")):
        m = json.loads(meta.read_text(encoding="utf-8"))
        name = m["name"]
        derived = []
        for k in ("albedo", "height", "roughness", "ao"):
            f = gen_dir / "derived" / ("%s_%s.png" % (name, k))
            if f.is_file():
                derived.append({"map": k,
                                "file": "materials/generated/derived/%s" % f.name,
                                "sha256": sha256(f), "bytes": f.stat().st_size,
                                "origin": "generated" if k == "albedo" else "derived"})
        entries.append({
            "id": "openai:" + name,
            "strategy": "openai-generated",
            "source": "openai-generated",
            "model": m["model"],
            "size": m["size"],
            "quality": m.get("quality"),
            "prompt": m["prompt"],
            "generatedOn": m["generatedOn"],
            "generatedMaps": m.get("generatedMaps", ["albedo"]),
            "derivedMaps": m.get("derivedMaps", []),
            "derivationTool": m.get("derivationTool"),
            "normalPolicy": m["normalPolicy"],
            "license": ("Generated with the OpenAI Images API by the project owner. "
                        "No third-party asset was redistributed to produce it."),
            "externalFiles": derived,
            "usedIn": "facade ornament / roof / plaster / shopfront timber",
        })

    payload = {
        "contract": "second-gate.town-material-provenance",
        "version": 1,
        "generatedOn": "2026-08-20",
        "note": ("Provenance for every material source used in the next town "
                 "gauntlet. Secrets are never recorded. Poly Haven assets are "
                 "CC0 (commercial use and redistribution permitted, attribution "
                 "optional), verified at polyhaven.com/license on 2026-08-20."),
        "strategyCounts": {
            "procedural": sum(1 for e in entries if e["strategy"] == "procedural"),
            "public-library": sum(1 for e in entries if e["strategy"] == "public-library"),
            "openai-generated": sum(1 for e in entries if e["strategy"] == "openai-generated"),
        },
        "materials": entries,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print("wrote %s  (%d materials: %s)" % (OUT, len(entries), payload["strategyCounts"]))


if __name__ == "__main__":
    main()
