"""Pack the guides and their prompts for generating plates by hand.

The API path needs credits; the ChatGPT web app does not, and it is currently the
better generator anyway -- a reasoning model that plans and then draws beats a
single images/edits call, and a twelve-word prompt with one reference beat two
hundred words of constraints. So this writes everything needed to do it by hand:
the style sheet, one guide per screen, and the exact text to paste.

Two things the short prompt deliberately keeps:

**Characters stay in.** They anchor the image semantically -- the model draws a
place people live in rather than an architectural render -- and a plate cannot
ship with the player baked in, so removal is a SECOND pass on the finished image
rather than a constraint on the first. Constraining the first pass is what made
the earlier attempts read as blockouts.

**The guide is described in one sentence.** It marks where things go; it is not a
picture to copy. Everything else about the look comes from the style sheet.

    python tools/asset-gen/export_plate_briefs.py \
        --positions out/town-positions \
        --style out/town-img2img/style-reference.png \
        --output out/town-guides
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

from PIL import Image

UPSCALE = 3          # guides are 240 rows tall; NEAREST so no line is invented

LEGEND = ("The second image is a layout guide, not a picture: the white line is "
          "the ground, the blue stick is how tall a person is, each red arrow "
          "marks a doorway, the green lines lie flat on the ground going away "
          "from you, and the amber lines stand upright. Follow where they go and "
          "draw none of them.")

FOLLOW_UP = ("Now remove the people, and change nothing else.")


def slug(title):
    return (title.replace("St. Maria - ", "").replace("/", "-")
            .replace(chr(39), "").replace(",", "").replace(" ", "-").lower())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--positions", required=True, type=Path)
    parser.add_argument("--style", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    manifest = json.loads((args.positions / "inputs.json").read_text(encoding="utf-8"))
    args.output.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(args.style, args.output / "00-style-reference.png")

    lines = [
        "# Plate briefs",
        "",
        "Generated by `tools/asset-gen/export_plate_briefs.py`. One guide per "
        "screen, plus the style sheet.",
        "",
        "**How to run one.** Upload `00-style-reference.png` FIRST, then that "
        "screen's guide, then paste the prompt. When the picture is right, send "
        "the follow-up to clear the figures out of it.",
        "",
        "**Characters are wanted in the first pass.** They anchor the image -- the "
        "model draws somewhere people live rather than an architectural render -- "
        "and they come out in the second pass. A plate cannot ship with the "
        "player painted into it.",
        "",
        "**Sizes matter on landing, not on generation.** Each screen names the "
        "width its plate must be. Whatever comes back gets resized to that, and "
        "the package's `imageSize` and `pixelsPerRuntimeY` move with it -- never "
        "before it, or the doorways slide off their anchors.",
        "",
        f"**Follow-up prompt, every screen:** `{FOLLOW_UP}`",
        "",
        "---",
        "",
    ]

    for frame in manifest["frames"]:
        guide = Image.open(args.positions / frame["file"]).convert("RGB")
        big = guide.resize((guide.width * UPSCALE, guide.height * UPSCALE),
                           Image.NEAREST)
        name = "%02d-%s-guide.png" % (frame["mapId"], slug(frame["title"]))
        big.save(args.output / name)

        intro = (frame.get("intro") or "").strip()
        prompt = ("Generate a screenshot for this game, in the same look as the "
                  "first image. " + (intro + " " if intro else "") + LEGEND)
        width, height = frame["plateSize"]
        lines += [
            "## %d. %s" % (frame["mapId"], frame["title"]),
            "",
            "- guide: `%s`" % name,
            "- plate must end up **%d x %d** (currently %s)"
            % (width, height, "x".join(str(v) for v in frame["currentPlateSize"])),
            "- doorways at: %s" % (", ".join(
                "%s %.0f%%" % (o["anchor"], 100 * o["fraction"])
                for o in frame.get("openings", [])) or "none"),
            "",
            "```",
            prompt,
            "```",
            "",
        ]

    (args.output / "PROMPTS.md").write_text("\n".join(lines), encoding="utf-8")
    print("PLATE BRIEFS OK screens=%d -> %s"
          % (len(manifest["frames"]), args.output))


if __name__ == "__main__":
    main()
