"""Pack the guides and their prompts for generating plates by hand.

The API path needs credits; the ChatGPT web app does not, and it is currently the
better generator anyway -- a reasoning model that plans and then draws beats a
single images/edits call, and a twelve-word prompt with one reference beat two
hundred words of constraints. So this writes everything needed to do it by hand:
the style sheet, one guide per screen, and the exact text to paste.

Two things the short prompt deliberately keeps:

**Characters stay in.** They anchor the image semantically -- the model draws a
place people live in rather than an architectural render -- and a plate cannot
ship with the player baked in, so removal is a SECOND pass on the finished image
rather than a constraint on the first. Constraining the first pass is what made
the earlier attempts read as blockouts.

**The guide is described in one sentence.** It marks where things go; it is not a
picture to copy. Everything else about the look comes from the style sheet.

    python tools/asset-gen/export_plate_briefs.py \
        --positions out/town-positions \
        --style out/town-img2img/style-reference.png \
        --output out/town-guides
"""

from __future__ import annotations

import argparse
import json
import shutil
import zipfile
from pathlib import Path

from PIL import Image

NEWLINE = chr(10)
UPSCALE = 3          # guides are 240 rows tall; NEAREST so no line is invented

# Written in the owner's voice, because the owner's voice worked. Theirs was
# "generate more screenshots for this game. focus on the 90's cgi look." -- twelve
# words, one reference, four coherent screens. Mine ran to two hundred words of
# constraints and produced blockouts.
#
# Note what that costs: the "no style words" rule this pipeline had been following
# is wrong at this length. One style cue, in plain words, alongside a reference
# that already shows it, does not fight the reference -- it agrees with it. What
# fights a reference is a paragraph of adjectives.
STYLE_CUE = "focus on the 90's cgi look"

# A clause, not a legend. Explaining every colour asks the model to read a
# diagram, which is how the diagram ends up in the picture. This says only what
# is fixed, and trusts it to see the rest.
GUIDE_CLAUSE = ("the second image is the layout -- keep the doors where the "
                "arrows are and the ground on the line, and don't draw the "
                "guide itself")

FOLLOW_UP = "now take the people out, change nothing else"


def look_prompt(intro):
    """No guide. For finding the screen, the way the owner's own run did."""
    return "generate a screenshot for this game%s. %s." % (
        (" -- " + intro.rstrip(".").lower()) if intro else "", STYLE_CUE)


def layout_prompt(intro):
    """The same, plus the one clause that pins the layout."""
    return "%s %s." % (look_prompt(intro), GUIDE_CLAUSE)


def slug(title):
    return (title.replace("St. Maria - ", "").replace("/", "-")
            .replace(chr(39), "").replace(",", "").replace(" ", "-").lower())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--positions", required=True, type=Path)
    parser.add_argument("--style", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--no-zips", action="store_true",
                        help="skip the per-screen archives")
    args = parser.parse_args()

    manifest = json.loads((args.positions / "inputs.json").read_text(encoding="utf-8"))
    args.output.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(args.style, args.output / "00-style-reference.png")

    briefs = []
    lines = [
        "# Plate briefs",
        "",
        "Generated by `tools/asset-gen/export_plate_briefs.py`. One guide per "
        "screen, plus the style sheet.",
        "",
        "**One screen at a time.** Upload `00-style-reference.png` first, then "
        "that screen's guide, then paste the prompt. When the picture is right, "
        "send the follow-up to clear the figures out of it.",
        "",
        "**Two prompts per screen.** The one with the guide fits a plate to its "
        "doorways; the one without goes looking for what the screen even is. "
        "Both are short on purpose -- twelve words and one reference beat two "
        "hundred words of constraints, which is how these were rewritten.",
        "",
        "**Characters are wanted in the first pass.** They anchor the image -- the "
        "model draws somewhere people live rather than an architectural render -- "
        "and they come out in the second pass. A plate cannot ship with the "
        "player painted into it.",
        "",
        "**Sizes matter on landing, not on generation.** Each screen names the "
        "width its plate must be. Whatever comes back gets resized to that, and "
        "the package's `imageSize` and `pixelsPerRuntimeY` move with it -- never "
        "before it, or the doorways slide off their anchors.",
        "",
        f"**Follow-up, every screen:** `{FOLLOW_UP}`",
        "",
        "---",
        "",
    ]

    for frame in manifest["frames"]:
        guide = Image.open(args.positions / frame["file"]).convert("RGB")
        big = guide.resize((guide.width * UPSCALE, guide.height * UPSCALE),
                           Image.NEAREST)
        name = "%02d-%s-guide.png" % (frame["mapId"], slug(frame["title"]))
        big.save(args.output / name)

        intro = (frame.get("intro") or "").strip()
        width, height = frame["plateSize"]
        screen = [
            "## %d. %s" % (frame["mapId"], frame["title"]),
            "",
            "- guide: `%s`" % name,
            "- plate must end up **%d x %d** (currently %s)"
            % (width, height, "x".join(str(v) for v in frame["currentPlateSize"])),
            "- doorways at: %s" % (", ".join(
                "%s %.0f%%" % (o["anchor"], 100 * o["fraction"])
                for o in frame.get("openings", [])) or "none"),
            "",
            "**With the guide** (style sheet, then the guide, then this):",
            "",
            "```",
            layout_prompt(intro),
            "```",
            "",
            "**Without it** (style sheet only, when the screen needs finding "
            "rather than fitting):",
            "",
            "```",
            look_prompt(intro),
            "```",
            "",
        ]
        lines += screen
        briefs.append({
            "mapId": frame["mapId"],
            "slug": slug(frame["title"]),
            "guide": name,
            "brief": NEWLINE.join(
                ["# %s" % frame["title"], "",
                 "Upload `00-style-reference.png` first, then `%s`, then paste a "
                 "prompt. When it looks right: `%s`" % (name, FOLLOW_UP), ""]
                + screen[1:]),
        })

    (args.output / "PROMPTS.md").write_text(NEWLINE.join(lines), encoding="utf-8")

    if not args.no_zips:
        # One archive per screen, each self-contained: the style sheet, that
        # screen's guide, and only that screen's prompts. Handing over the whole
        # folder invites generating the whole town as one picture -- which the
        # web app will happily do, and which is interesting -- but a plate has to
        # be its own image at its own size, so the unit of handoff is the plate.
        archives = args.output / "zips"
        archives.mkdir(exist_ok=True)
        style = args.output / "00-style-reference.png"
        for entry in briefs:
            path = archives / ("%02d-%s.zip" % (entry["mapId"], entry["slug"]))
            with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as bundle:
                bundle.write(style, style.name)
                bundle.write(args.output / entry["guide"], entry["guide"])
                bundle.writestr("PROMPT.md", entry["brief"])
        with zipfile.ZipFile(args.output / "all-plates.zip", "w",
                             zipfile.ZIP_DEFLATED) as bundle:
            for path in sorted(archives.glob("*.zip")):
                bundle.write(path, path.name)
        print("  %d per-screen archives + all-plates.zip" % len(briefs))

    print("PLATE BRIEFS OK screens=%d -> %s"
          % (len(manifest["frames"]), args.output))


if __name__ == "__main__":
    main()
