#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"projects"/"hichaukitoden-game"/"assets"/"models"/"metro"
COLORS={"blue":(.08,.35,.82),"green":(.05,.55,.22),"red":(.78,.08,.08),"yellow":(.92,.68,.04),"lilac":(.55,.20,.68)}
def material(rgb):
 r,g,b=(f"{v:.3f}" for v in rgb);return f"""# Generated by tools/generate_metro_train_models.py
newmtl body
Ka 0.180 0.180 0.190
Kd 0.620 0.630 0.650
Ks 0.120 0.120 0.120
illum 2

newmtl stripe
Ka {r} {g} {b}
Kd {r} {g} {b}
Ks 0.100 0.100 0.100
illum 2

newmtl dark
Ka 0.030 0.035 0.045
Kd 0.070 0.080 0.100
Ks 0.080 0.080 0.100
illum 2
"""
def model(key,state):
 lines=["# Generated by tools/generate_metro_train_models.py",f"mtllib metro_train_{key}.mtl",f"o metro_train_{key}_{state}","vt 0.0 0.0"];vi=ni=0
 def quad(mat,a,b,c,d,n):
  nonlocal vi,ni;lines.append(f"usemtl {mat}")
  for p in (a,b,c,d):lines.append("v "+" ".join(f"{v:.6f}" for v in p))
  lines.append("vn "+" ".join(f"{v:.6f}" for v in n));ni+=1;s=vi+1;vi+=4;lines.extend((f"f {s}/1/{ni} {s+1}/1/{ni} {s+2}/1/{ni}",f"f {s}/1/{ni} {s+2}/1/{ni} {s+3}/1/{ni}"))
 def box(mat,x0,x1,y0,y1,z0,z1):
  quad(mat,(x0,y0,z0),(x1,y0,z0),(x1,y1,z0),(x0,y1,z0),(0,0,-1));quad(mat,(x0,y0,z1),(x0,y1,z1),(x1,y1,z1),(x1,y0,z1),(0,0,1));quad(mat,(x0,y0,z0),(x0,y0,z1),(x1,y0,z1),(x1,y0,z0),(0,-1,0));quad(mat,(x0,y1,z0),(x1,y1,z0),(x1,y1,z1),(x0,y1,z1),(0,1,0));quad(mat,(x0,y0,z0),(x0,y1,z0),(x0,y1,z1),(x0,y0,z1),(-1,0,0));quad(mat,(x1,y0,z0),(x1,y0,z1),(x1,y1,z1),(x1,y1,z0),(1,0,0))
 for c in (-3,0,3):
  box("body",c-1.45,c+1.45,-.44,.44,0,.08);box("body",c-1.45,c+1.45,-.44,.44,.78,.90);box("body",c-1.45,c+1.45,-.44,-.40,.08,.27);box("body",c-1.45,c+1.45,.40,.44,.08,.27);box("stripe",c-1.45,c+1.45,-.455,-.44,.50,.58);box("stripe",c-1.45,c+1.45,.44,.455,.50,.58)
  for side in (-1,1):
   y0,y1=(-.45,-.42) if side<0 else (.42,.45);box("body",c-1.45,c-.52,y0,y1,.27,.78);box("body",c+.52,c+1.45,y0,y1,.27,.78)
   if state=="closed":box("dark",c-.50,c+.50,y0,y1,.27,.76)
 box("body",-4.50,-4.42,-.44,.44,.08,.78);box("body",4.42,4.50,-.44,.44,.08,.78);return "\n".join(lines)+"\n"
def products():
 out={}
 for key,rgb in COLORS.items():out[f"metro_train_{key}.mtl"]=material(rgb);out[f"metro_train_{key}_open.obj"]=model(key,"open");out[f"metro_train_{key}_closed.obj"]=model(key,"closed")
 return out
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--check",action="store_true");args=ap.parse_args();expected=products()
 if args.check:
  bad=[n for n,b in expected.items() if not (OUT/n).exists() or (OUT/n).read_text(encoding="utf-8")!=b]
  if bad:raise SystemExit("metro model products are stale: "+", ".join(bad))
  print("METRO MODEL PRODUCTS OK");return
 OUT.mkdir(parents=True,exist_ok=True)
 for n,b in expected.items():(OUT/n).write_text(b,encoding="utf-8",newline="\n")
 print(f"generated {len(expected)} metro model products")
if __name__=="__main__":main()
