from pathlib import Path

path = Path("presentation/viewport_3d.lua")
text = path.read_text(encoding="utf-8")
old = '''local function drawSkyBackdrop(atlas, screenWpx, screenHpx, cameraAngle)\n    if atlas and atlas.skyPanorama then\n        local img = getPanoramaImage(atlas.skyPanorama)\n        if img then\n            local iw, ih = img:getDimensions()\n            local backdropH = math.floor(screenHpx * 0.5)\n            local scale = backdropH / ih\n            local sourceW = screenWpx / scale\n            local turn = ((cameraAngle or 0) / (math.pi * 2)) % 1\n            local sourceX = turn * iw\n            if not panoramaQuad then panoramaQuad = love.graphics.newQuad(0, 0, 1, 1, 1, 1) end\n            panoramaQuad:setViewport(sourceX, 0, sourceW, ih, iw, ih)\n            love.graphics.setColor(1, 1, 1, 1)\n            love.graphics.draw(img, panoramaQuad, 0, 0, 0, scale, scale)\n            return true\n        end\n    end\n    if not atlas or not atlas.skyTiles or #atlas.skyTiles == 0 then return false end\n    local backdropH = math.floor(screenHpx * 0.5)\n    local scale = backdropH / ATLAS_TILE\n    local tileW = ATLAS_TILE * scale\n    local x = 0\n    local tileIndex = 1\n    love.graphics.setColor(1, 1, 1, 1)\n    while x < screenWpx do\n        local tile = atlas.skyTiles[tileIndex]\n        skyQuad:setViewport(tile[2] * ATLAS_TILE, tile[1] * ATLAS_TILE,\n            ATLAS_TILE, ATLAS_TILE, atlas.w, atlas.h)\n        love.graphics.draw(atlas.img, skyQuad, x, 0, 0, scale, scale)\n        x = x + tileW\n        tileIndex = (tileIndex % #atlas.skyTiles) + 1\n    end\n    return true\nend\n'''
new = '''local function drawSkyBackdrop(atlas, screenWpx, screenHpx, cameraAngle)\n    -- Sky sampling is authored against the canonical composition. A wider\n    -- render surface reveals samples to the left/right of that old crop; it\n    -- must not restart or rescale the sky at physical target x=0.\n    local originX = surface.compositionOriginX()\n    if atlas and atlas.skyPanorama then\n        local img = getPanoramaImage(atlas.skyPanorama)\n        if img then\n            local iw, ih = img:getDimensions()\n            local backdropH = math.floor(surface.compositionHeight() * 0.5)\n            local scale = backdropH / ih\n            local sourceW = screenWpx / scale\n            local turn = ((cameraAngle or 0) / (math.pi * 2)) % 1\n            local sourceX = turn * iw - originX / scale\n            if not panoramaQuad then panoramaQuad = love.graphics.newQuad(0, 0, 1, 1, 1, 1) end\n            panoramaQuad:setViewport(sourceX, 0, sourceW, ih, iw, ih)\n            love.graphics.setColor(1, 1, 1, 1)\n            love.graphics.draw(img, panoramaQuad, 0, 0, 0, scale, scale)\n            return true\n        end\n    end\n    if not atlas or not atlas.skyTiles or #atlas.skyTiles == 0 then return false end\n    local backdropH = math.floor(surface.compositionHeight() * 0.5)\n    local scale = backdropH / ATLAS_TILE\n    local tileW = ATLAS_TILE * scale\n    -- Tile index zero is anchored at canonical composition x=0. Start far\n    -- enough left to cover the render surface, including negative canonical\n    -- coordinates exposed by Wide. Lua's modulo keeps the repeat index positive.\n    local tileNumber = math.floor(-originX / tileW)\n    local x = originX + tileNumber * tileW\n    love.graphics.setColor(1, 1, 1, 1)\n    while x < screenWpx do\n        local tileIndex = (tileNumber % #atlas.skyTiles) + 1\n        local tile = atlas.skyTiles[tileIndex]\n        skyQuad:setViewport(tile[2] * ATLAS_TILE, tile[1] * ATLAS_TILE,\n            ATLAS_TILE, ATLAS_TILE, atlas.w, atlas.h)\n        love.graphics.draw(atlas.img, skyQuad, x, 0, 0, scale, scale)\n        tileNumber = tileNumber + 1\n        x = originX + tileNumber * tileW\n    end\n    return true\nend\n'''
if text.count(old) != 1:
    raise RuntimeError(f"expected one sky backdrop block, found {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8", newline="\n")
Path("tools/issue199_sky_fix.py").unlink()
Path(".github/workflows/issue199-sky-fix.yml").unlink()
print("sky phase anchored to canonical composition")
